### PR TITLE
feat(nx-plugin): Release automation

### LINKED ISSUE #55: Release automation
semantic-release doesn't support monorepos and I'm not super excited about any of the forks, however https://github.com/googleapis/release-please looks like a good option!

I think it should make sense to add a generator for this to our nx plugin (which we should use in this repo!)

### PR DESCRIPTION
**Pull request by luxaritas**
One particular open question: Currently I have things set up with the license and release generators such that they set defaults for themselves on first run, so that when the package generator runs the per-package related code, it pulls from that. Should we instead extract out those operations such that we have `license-core`/`license-package` and `release-core`/`release-package`, with the defaults set on the `-package` generators? That would make the behavior of re-running one of these generators a bit less odd (ie, applying parameters from however you last ran it rather than re-prompting).

That would bring up a further question though: who would be responsible for applying the defaults from the nx.json? When running the generators via the command line, nx itself would do that. Maybe we make the TS interface such that those options are optional, and if not specified then it looks for defaults? The other option, which is more conventional for nx, would be to have the license and release options on every parent generator (eg, instead of just package, it would also be on lib-ts, app-node, etc like name, description, etc are) - though that would mean not just adding it to the schema of each (which is kinda cool since that means we could override the default behavior when we generate a package), but also means we'd need to set these as default values for _each generator_, which while elegant from an execution standpoint (we never have to inspect the nx.json ourselves) means a lot of extra configuration.

Side note: I filed https://github.com/nrwl/nx/issues/10890 with nx a while back to note that this behavior could be improved by providing a utility in devkit to say "this generator runs this other generator, please raise its arguments and handle things like defaults and prompts for me"

Resolves #55

### CODE REVIEW

**Comment by luxaritas** [comment]
Another thought: Should I look into setting up some workflow that runs on every commit to main to create canary releases? The idea would be that it would, say, bump every package version one minor version and add something like `-dev.<n>` and release it to npm under the `canary` tag so that we could install and test in another project. I wouldn't want to use release-please though as I'd want it to auto-publish instead of requiring a PR merge. Theoretically we could pull in lerna and do a `lerna publish --canary --preid dev` though I'd need to do a bit of testing (make sure it works appropriately given release-please uses lightweight tags and not annotated tags, plus ensuring its behavior of updating other packages which may be dependent on it makes sense)

**Comment by luxaritas** [comment]
Sorry, bump one patch version, not minor version.

Looking through the lerna source, it appears that it should work properly - I'm inclined to add canary publishing to this PR tomorrow. That should also make it easier for us to test our changes since we'll have a dev version pushed to npm! Also happy to hear suggestions about semver and tag names. `-dev`? `-next`? `-beta`? `@canary`? `@next`?

**Comment by luxaritas** [comment]
Ok so one thing worth noting about doing the canary without annotated tags. In my testing repo, the previous commit was tagged, and we get this:
```
npx lerna publish --canary --preid dev
lerna notice cli v5.3.0
lerna info versioning independent
lerna info canary enabled
lerna info Looking for changed packages since 14770f3^..14770f3

Found 8 packages to publish:
 - @eternagame/bootstrap => 1.0.1-dev.161+14770f3
 - @eternagame/eslint-plugin => 2.0.1-dev.161+14770f3
 - @eternagame/jest-utils => 2.0.1-dev.161+14770f3
 - @eternagame/lint-staged-utils => 1.0.1-dev.161+14770f3
 - @eternagame/nx-plugin => 2.0.1-dev.161+14770f3
 - @eternagame/nx-spawn => 2.0.1-dev.161+14770f3
 - @eternagame/tsconfig => 2.0.1-dev.161+14770f3
 - @eternagame/vite-utils => 2.0.1-dev.161+14770f3
 ```
There's a couple reasons for this:
1) Lerna is looking for annotated tags, but release-please has github make the tags as part of creating a github release, which uses lightweight tags. We'd need to convert the tags to annotated as part of the release process by running something like `git for-each-ref refs/tags/ --format '%(objecttype) %(refname:short)' | while read tagtype tag; do [ $tagtype = commit ] && git tag -a $tag $tag -m $tag -f; done` (cf https://stackoverflow.com/questions/21031201/how-can-i-list-all-lightweight-tags)
2) In independent mode, lerna searches for the last tag like `@<scope>/<pkg>@*` whereas release-please makes them `<pkg>-*`.  I think we can get release-please to use that format by setting `tag-separator` to `@` and manually setting `component` to the full package name with scope for each package in the release-please-config. The question is whether or not we want to. I know we originally discussed preferring the format like `@eternagame/bootstrap@1.0.0` (which also suggests setting `include-v-in-tag` to false), though the current tagging of `bootstrap-v1.0.0` seems a little more friendly... Maybe that's just me?

**Comment by luxaritas** [comment]
Decisions discussed in call:
- For simplicity, don't worry about a "correct" build number. No one will really care
- `-dev` and `@canary`
- Use the default release-please tags

**Comment by tkaragianes** [comment]
Code reviewed on call.

**Review by tkaragianes — APPROVED** [review]

**Pull request merged**
