### PR TITLE
fix(jest-utils,nx-plugin): Fix running jest config, test:cov nx configuration, and path resolution in tests

### PR DESCRIPTION
**Pull request by luxaritas**
Few things this addresses:
* Jest requires ts-node to use ts configuration files. This is now added in the relevant generator
* Jest currently forces ts configuration files to be compiled as CJS. This means we have to compile jest-utils as CJS, as otherwise we won't be able to import it (as you can't `require` ESM from CJS). See https://github.com/facebook/jest/issues/13118
* Only `test` was properly set up with nx (caching/dependencies/inputs/outputs), `test:cov` now is as well

### CODE REVIEW

**Comment by luxaritas** [comment]
As a note: I am up for discussion about whether we really want to require ts-node. On a brief test, it does appear that we're getting proper autocomplete on JS files in VSC since it's able to pick up on the types from jest-utils, and we could just add `// @ts-check` to force the editor to report type errors

**Comment by luxaritas** [comment]
After discussion, we've agreed that there's not really a benefit for adding `ts-node` - we'll stick with js configs and `// @ts-check`. I'll also probably work on #119 in this PR as well so that all the config changes are centralized

**Comment by luxaritas** [comment]
So using a root config was a bust, but I realized something else - if we had something like
```
src/
  mod/
      mod.ts
  index.ts
```
and index.ts imported `'mod/mod'`, running a jest test importing index would throw a module resolution error. I had to explicitly set both the baseUrl in the spec tsconfig (so the TS compiler would see it) and the modulePaths property in the jest config (so that jest knows how to resolve it). If we wanted to be more robust for the use case of

**Review by tkaragianes — APPROVED** [review]

**Comment by muratkorkmaz106** [comment]
Start

**Review by muratkorkmaz106 — COMMENTED** [review]
Start

**Pull request merged**
